### PR TITLE
[REF] Convert from context-based to step-based checkpointing trigger

### PR DESCRIPTION
**Pull request by scottclowe**
Refactors the code to use a step method on the checkpoint handler instead of a context.

### CODE REVIEW

**Review by f-dangel — COMMENTED** [review]
Minor comments.

One thing I would ask you to do is to change the pattern of the checkpoint path from `f'{self.run_id}_epoch_{epoch}.pt'` to `f'{self.run_id}_step_{self.step_count}.pt'`. You will then also have to modify the function that figures out the most recent checkpoints, as it makes assumption about the checkpoint path's structure to extract the step.

**Comment by scottclowe** [comment]
I was planning to drop all references to epoch in a second PR that adds more changes that are necessary for correctly resuming from unscheduled pre-emption, but we could add it here instead.

I was thinking of changing the checkpoint format to be `f'{self.run_id}_{self.step_count}.pt'` instead, which simply doesn't indicate the units of checkpointing intervals. I think referring to "step" explicitly could be confusing if checkpoints are only done once per epoch, as step suggests to me every batch.

**Comment by scottclowe** [comment]
I fixed references to the context manager that persisted in some docstrings (force push) and added code that changes references to epoch to be more generic "checkpoint_step". Note that this has the side-effect of changing epochs to be indexed from 1 instead of from 0 as that made the most sense (see the commit message for details).

**Comment by f-dangel** [comment]
Looks mostly good. I'm still trying to argue with myself why first increasing the counter, then saving the checkpoint, is better than the other way round. I think I prefer having the first checkpoint being indexed with zero rather than one. I think this should lead to less `+ 1`s in the example, too.

**Comment by scottclowe** [comment]
Okay, I removed the change in epoch indexing from the PR. Note that the return value description for `load_latest_checkpoint` still refers to it as "The epoch number at which training should resume." for now, since I can't think of any other way to succinctly describe what the return value means.

**Review by f-dangel — APPROVED** [review]
LGTM.

**Pull request merged**
