### PR TITLE
[TEST] Add integration test for training script

### PR DESCRIPTION
**Pull request by f-dangel**

### CODE REVIEW

**Comment by scottclowe** [comment]
Do we want the tests to run in a dev version of the code only (a clone of the git repo), or should they run for pip installs too?

**Comment by f-dangel** [comment]
I think dev version is fine. Would consider the `walkthrough` as a more approachable test a user can carry out.

**Comment by scottclowe** [comment]
The reason I ask is because if we want the tests to run when the code is pip installed, we would need to add example/ to the MANIFEST.in (or pyproject.toml equivalent config setting) so they are copied to `pythonX/site-packages/wandb_preempt/`. Not sure if we should do that anyway.

**Comment by f-dangel** [comment]
Maybe the best place for the example is inside the `docs/` folder?

**Comment by scottclowe** [comment]
I think its good to have it in a separate dir from docs

**Comment by f-dangel** [comment]
Feel free to merge or propose further changes

**Pull request merged**
